# Schema for the configuration files of the MET NIWA module.
met_niwa.settings:
  type: config_object
  label: 'MET NIWA settings'
  mapping:
    url:
      type: string
      label: 'URL'
    endpoint:
      type: string
      label: 'Endpoint'
    tbu:
      type: string
      label: 'Tongatapu'
    hpp:
      type: string
      label: 'Haapai'
    vv:
      type: string
      label: 'Vavau'
    eua:
      type: string
      label: 'Eua'
