tasks:
  - init: |
      sudo chown gitpod:gitpod .
      curl -O https://gist.githubusercontent.com/ainsofs/ba947741b230606be5d2f4aad6faf7bf/raw/.bash_aliases
      source .bash_aliases
      cp .env .env.gitpod
      sed -i "s|PROJECT_BASE_URL=tms.docker.localhost|PROJECT_BASE_URL=${GITPOD_WORKSPACE_URL}|g" .env.gitpod
      sed -i "s|PROJECT_BASE_URL=https://|PROJECT_BASE_URL=8000-|g" .env.gitpod
      make gitpod
      make composer "install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist"
      make composer build
      make drush uli
    command: |
      source .bash_aliases
      make gitpod

# VScode xdebug extension
vscode:
  extensions:
    # PHP extensions.
    - felixfbecker.php-debug
    - wongjn.php-sniffer
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client
    - devsense.composer-php-vscode

    # Bash extensions.
    # - timonwong.shellcheck
    # - rogalmic.bash-debug

    # Vue extensions.
    # - vue.volar

    # AI extensions.
    # - codeium.codeium

ports:
  # project port
  - port: 8000
    onOpen: open-browser
  # mailhog port
  - port: 8025
    onOpen: open-browser