name: met-api
recipe: drupal10
config:
  webroot: .
  php: 8.2
services:
  node:
    type: node:20
    build_as_root:
      - npm install & npm install -g newman
  db:
    type: "mysql:5.7"
    portforward: false
    creds:
      user: mysql
      password: mysql
      database: database
  phpmyadmin:
    type: phpmyadmin
    backends: [db]
tooling:
  npm:
    service: node
  node:
    service: node
  newman:
    service: node
