name: met-api
recipe: drupal10
config:
  webroot: .
  php: 8.1
services:
  db:
    type: 'mysql:5.7'
    portforward: false
    creds:
      user: mysql
      password: mysql
      database: database
  phpmyadmin:
    type: phpmyadmin
    backends: [db]
