services:
  php:
    # image: wodby/drupal:$DRUPAL_TAG
    environment:
      PHP_FPM_CLEAR_ENV: "no"
      # API Keys
      FB_SERVER_KEY: ''
      FB_SENDER_ID: ''

  mariadb:
    volumes:
      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.

  # pma:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: "${PROJECT_NAME}_pma"
  #   environment:
  #     PMA_HOST: $DB_HOST
  #     PMA_USER: $DB_USER
  #     PMA_PASSWORD: $DB_PASSWORD
  #     UPLOAD_LIMIT: 1G
  #   labels:
  #   - "traefik.http.routers.${PROJECT_NAME}_pma.rule=Host(`pma.${PROJECT_BASE_URL}`)"

