# Schema for the configuration files of the MET Service module.
met_service.settings:
  type: config_object
  label: 'MET Service settings'
  mapping:
    host:
      type: string
      label: 'Host'
    port:
      type: string
      label: 'Port'
