name: PHPUnit Tests

on:
  - pull_request
  - push

env:
  LANDO_VERSION: v3.21.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Grab latest Lando CLI
        run: |
          sudo curl -fsSL -o /usr/local/bin/lando "https://files.lando.dev/cli/lando-linux-x64-${LANDO_VERSION}"
          sudo chmod +x /usr/local/bin/lando

      # This is optional.
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      # Boot Lando and set up Drupal
      - run: lando start
      - run: lando composer install
      - run: lando composer require --dev drupal/core-dev
      - run: lando ssh --command "cp modules/custom/met_api/test/modules/met_api_test/assets/phpunit.xml core/phpunit.xml"
      - run: lando ssh --command "cp core/.env.example .env"

      # Install Drupal
      - run: lando drush si -y --db-url=mysql://drupal10:drupal10@database:3306/drupal10
      - run: lando drush cset system.site uuid "5bb79423-cfb5-4dd1-98fc-1efb2a54c645" -y
      - run: lando drush entity:delete shortcut_set
      - run: lando drush en paragraphs met_warning met_tk -y
      - run: lando drush cim --source=config/site -y

      # Set private file path
      - run: lando ssh --command 'mkdir /var/www/private'
      - run: lando ssh --command 'chmod 744 /app/sites/default/settings.php'
      - run: lando ssh --command 'ls -la /app/sites/default/'
      - run: lando ssh --command 'echo \$settings[\"file_private_path\"] = \"/var/www/private\"\; >> /app/sites/default/settings.php'
      - run: lando drush cr

      # Run NIWA API to fetch weather data
      - name: Fetch weather data from NIWA API
        run: lando ssh --command "curl 'http://met-api.lndo.site/met-niwa/run'"

      - name: Fetch tide data from SPC API
        run: lando ssh --command "curl 'http://met-api.lndo.site/met-spc/run'"
jobs: 
  test:
    steps:
      # Enable the test module
      - run: lando drush en met_api_test

      # This will run tests. If any tests fail, it will fail here.
      - name: Run tests TMS API
        run: lando composer test-tms-api

      - name: Run tests NIWA API
        run: lando composer test-niwa-api

      - name: Run tests SPC API
        run: lando composer test-spc-api
