name: PHPUnit Tests

on:
  - pull_request
  - push

env:
    LANDO_VERSION: v3.21.0

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Grab latest Lando CLI
              run: |
                    sudo curl -fsSL -o /usr/local/bin/lando "https://files.lando.dev/cli/lando-linux-x64-${LANDO_VERSION}"
                    sudo chmod +x /usr/local/bin/lando

            # This is optional.
            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-

          
            # Boot Lando and set up Drupal
            - run: lando start
            - run: lando composer install
            - run: lando composer require --dev drupal/core-dev
            - run: lando ssh --command "cp .github/workflows/phpunit.xml core/phpunit.xml"
            - run: lando ssh --command "cp core/.env.example .env"
            - run: lando info
            - run: lando drush si -y --db-url=mysql://drupal10:drupal10@database:3306/drupal10
            - run: lando drush cr

            # This will run tests. If any tests fail, it will fail here.
            - name: Run tests TMS API
              run: lando composer test-tms-api

            - name: Run tests NIWA API
              run: lando composer test-niwa-api

            - name: Run tests SPC API
              run: lando composer test-spc-api