name: PHPUnit Tests

on:
  - pull_request
  - push

env:
    LANDO_VERSION: v3.21.0
    APP_ENV: testing
    APP_DEBUG: true
    DB_CONNECTION: mysql
    DB_HOST: database
    DB_PORT: 3306
    DB_DATABASE: drupal10
    DB_USERNAME: drupal10
    DB_PASSWORD: drupal10

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Grab latest Lando CLI
              run: |
                    sudo curl -fsSL -o /usr/local/bin/lando "https://files.lando.dev/cli/lando-linux-x64-${LANDO_VERSION}"
                    sudo chmod +x /usr/local/bin/lando

            # This is optional.
            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-

            # Map GH Actions env vars into Lando env vars, which wil then be injected
            # into the application container.
            - run: |
                  cat > .lando.local.yml <<EOF
                  services:
                      appserver:
                          overrides:
                              environment:
                                  APP_ENV: '$APP_ENV'
                                  APP_DEBUG: '$APP_DEBUG'
                                  DB_CONNECTION: $DB_CONNECTION
                                  DB_HOST: $DB_HOST
                                  DB_PORT: $DB_PORT
                                  DB_DATABASE: $DB_DATABASE
                                  DB_USERNAME: $DB_USERNAME
                                  DB_PASSWORD: $DB_PASSWORD
                  EOF

            # Boot Lando and set up Laravel
            - run: lando start
            - run: lando composer install
            - run: lando composer require --dev drupal/core-dev
            - run: lando ssh --command "cp .github/workflows/phpunit.xml core/phpunit.xml"
            - run: lando ssh --command "cp .env.example .env"
            - run: lando drush site:install -y
            - run: lando drush cr

            # This will run tests. If any tests fail, it will fail here.
            - name: Run tests TMS API
              run: lando composer test-tms-api

            - name: Run tests NIWA API
              run: lando composer test-niwa-api

            - name: Run tests SPC API
              run: lando composer test-spc-api